### ISSUE TITLE
后台登入bug

### ISSUE THREAD

**Issue by usagiryu** [maysrp/TALD#1]
数据库已确保链接正确，默认admin 密码233无法登入后台，提示 ？请的输入正确的用户名？

**Comment by usagiryu** [comment]
尝试过自己插入一条新的用户，依然无解

**Comment by maysrp** [comment]
不要回车~~ 点击登入

**Comment by usagiryu** [comment]
解决了。Cherrs！
给您的邮箱里发送了一条邮件，请查收！
maysrp@gmail.com
